name: Deploy to ec2
env:
  AWS_REGION: us-east-2
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: connect
        run: ssh ec2-user@ec2-3-133-98-24.us-east-2.compute.amazonaws.com
      
       
   
      

